basePath: /api
definitions:
  model.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  service.AddRoleModel:
    properties:
      code:
        description: 角色code
        type: string
      name:
        description: 角色名
        type: string
    type: object
  service.LoginModel:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  service.RegisterModel:
    properties:
      nickname:
        description: 用户昵称
        type: string
      password:
        description: 用户登录密码
        type: string
      username:
        description: 用户登录名
        type: string
    type: object
host: 127.0.0.1:8889
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: docker监控服务后端API接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Docker监控服务
  version: "1.0"
paths:
  /account/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登入
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.LoginModel'
      produces:
      - application/json
      responses:
        "200":
          description: 返回空对象
          schema:
            $ref: '#/definitions/model.Response'
      summary: 登入
      tags:
      - account
  /account/regist:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.RegisterModel'
      produces:
      - application/json
      responses:
        "200":
          description: 返回空对象
          schema:
            $ref: '#/definitions/model.Response'
      summary: 注册
      tags:
      - account
  /account/role/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: roleModel
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.AddRoleModel'
      produces:
      - application/json
      responses:
        "200":
          description: 返回空对象
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加角色
      tags:
      - account
  /account/role/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 返回空对象
          schema:
            $ref: '#/definitions/model.Response'
      summary: 角色列表
      tags:
      - account
swagger: "2.0"
